apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: mas
  app.kubernetes.io/component: platform

images:
  - name: gitea0213.kro.kr/bluemayne/mas
    newTag: latest

