apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mas-api-keys.yaml
  - mas-postgres.yaml
  - postgresql-root-password.yaml

