apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - namespace.yaml
  - ../vault/mas-api-keys.yaml
  - ../vault/mas-postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

