apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mas-postgres
  namespace: mas
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mas-postgres
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: mas/postgres
        property: PASSWORD

