apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-password
  namespace: mas
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgresql-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: databases/postgresql
        property: PASSWORD
    - secretKey: postgres-password
      remoteRef:
        key: databases/postgresql
        property: POSTGRES_PASSWORD

