apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mas-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mas0213.kro.kr
    - www.mas0213.kro.kr
    secretName: mas-tls
  rules:
  - host: mas0213.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8000
  - host: www.mas0213.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mas
            port:
              number: 8000
