apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - ../../base
  - namespace.yaml
  - resourcequota.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정 (ArgoCD Image Updater가 자동으로 업데이트)
images:
  - name: harbor.mayne.vcn/mas/platform
    newTag: latest

