apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - ../../base
  - namespace.yaml
  - resourcequota.yaml
  - externalsecret.yaml
  - serviceaccount.yaml

commonLabels:
  environment: production

# 이미지 태그 설정 (ArgoCD Image Updater가 자동으로 업데이트)
images:
  - name: gitea0213.kro.kr/bluemayne/mas
    newTag: main-sha-16e2dc2153719146680c0f8519e8350a31f2c843

