apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - ../../base
  - resourcequota.yaml
  - externalsecret.yaml
  - ingress.yaml

commonLabels:
  environment: production

# 이미지 태그 설정 (ArgoCD Image Updater가 자동으로 업데이트)
images:
  - name: ghcr.io/mayne0213/mas
    newName: ghcr.io/mayne0213/mas
    newTag: main-sha-f9e224d1babebeb86275a65872bb9980b8ebff5f

