apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - ../../base
  - namespace.yaml
  - resourcequota.yaml
  - externalsecret.yaml
  - serviceaccount.yaml
  - ../../../vault/mas-postgres.yaml

commonLabels:
  environment: production

# 이미지 태그 설정 (ArgoCD Image Updater가 자동으로 업데이트)
images:
  - name: gitea0213.kro.kr/bluemayne/mas
    newTag: main-sha-ea42d1b2e4dcaea223cf4dbdbc6eaa315ee1eeef

