apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mas

resources:
  - ../../base
  - resourcequota.yaml
  - externalsecret.yaml

commonLabels:
  environment: production

# 이미지 태그 설정 (ArgoCD Image Updater가 자동으로 업데이트)
images:
  - name: gitea0213.kro.kr/bluemayne/mas
    newTag: main-sha-4fbb4262e0d1298b169627b959098dfef2aff666

